### ISSUE TITLE
Typo chapter 16

### ISSUE THREAD

**Issue by ClausLJ** [SethClydesdale/genki-study-resources#10]
On page https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-16/literacy-7/

Page 2 column 7 you write あんた but in the book it is あなた. 

Great site by the way! I use the "raw" text to paste into a word document and then make grammar and translation notes to prepare for Japanese class and eventually the exam.

**Comment by SethClydesdale** [comment]
Hi @ClausLJ,

Thank you for the report! This typo should now be corrected. ✔️ 

Thanks, I'm glad to hear it's helping you out. 

Have a good day, and do your best on the exam!
