### ISSUE TITLE
Wrong fugirana for 好

### ISSUE THREAD

**Issue by Ronserruya** [SethClydesdale/genki-study-resources#105]
Hey, all the questions in this quiz have the wrong furigana for "好", it shows すき, instead of just す.

https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/grammar-11/

![Screenshot 2020-10-24 200637](https://user-images.githubusercontent.com/21235163/97087820-8c6d8e80-1635-11eb-80ea-2efed220b82f.png)

**Comment by SethClydesdale** [comment]
Hello @Ronserruya,

Thanks for reporting this typo! @ingemarberg made a PR that should correct it (thanks!).

Gonna also run a full scan on the 3rd ed. files to see if I made any other mistakes like this. I gotta remember to double and triple check, and increase my coffee intake in the morning to spot these before pushing! haha

(will also check the furigana settings for the ruby tags, too; looks like a text alignment issue in your screenshot, so might revert to default settings)
