### ISSUE TITLE
Numbers with more than one separator are not parsed correctly

### ISSUE THREAD

**Issue by ingemarberg** [SethClydesdale/genki-study-resources#107]
Numbers with more than one separator do not seem to be parsed correctly. The answer is always marked as incorrect, even if the student writes the suggested answer. Numbers with a single separator are not affected by this bug. This error occurs in at least the following exercises:

**lesson-1/grammar-10**
- Exercise: ゼロにゼロのろくきゅうにいちのよんにさんろく
- Suggested answer: 020(-/)6921(-/)4236
- Answers marked as wrong: 02069214236, 020-69214236, 0206921-4236, 020-6921-4236

**lesson-1/grammar-10**
- Exercise: ゼロさんゼロのはちごににのいちゼロさんに
- Suggested answer: 030(-/)8522(-/)1032
- Answers marked as wrong: 03085221032, 030-85221032, 0308522-1032, 030-8522-1032

**lesson-1/workbook-4**
- Exercise: ゼロにゼロのろくきゅうにいちのよんにさんろく
- Suggested answer: 020(-/)6921(-/)4236
- Answers marked as wrong: 02069214236, 020-69214236, 0206921-4236, 020-6921-4236

**Comment by SethClydesdale** [comment]
Hello @ingemarberg,

Thanks for reporting this issue! This appears to be an oversight on my part, as the special sub answer group `%(/)` can only be used once per answer, so the second is ignored and taken literally as a part of the real answer. This means 020-6921%(-/)4236 or 0206921%(-/)4236 is seen as the correct answer by the [`Genki.check.answers`](https://github.com/SethClydesdale/genki-study-resources/blob/521fc6183c456efca97ff78350612ec78d9c66a9/resources/javascript/genki.js#L1569) function. In the case where `%(/)` needs to be used twice, `Genki.alts` is used instead as the third/fourth/etc. "hidden" answer array.

I should have the fix up for these answers in a little while. 👍 

Thanks again!

**Comment by SethClydesdale** [comment]
https://github.com/SethClydesdale/genki-study-resources/commit/c19d6fd573130e75acd5817565e2a08478b8266c should correct the issue! ✔️

**Comment by ingemarberg** [comment]
Great, I'm glad you were able to fix this bug so fast. Thanks once again for all your hard work!
