### ISSUE TITLE
Error in practice quiz

### ISSUE THREAD

**Issue by drajguru** [SethClydesdale/genki-study-resources#110]
I think there is an error in this lesson:

https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-4/grammar-8/

メアリーさんは水曜日すいようびにテニスをしましたか。

I believe the correct answer is B however it flags this response as incorrect.

**Comment by SethClydesdale** [comment]
Hello @drajguru,

Thanks for reporting this! It appears I forgot to mark one of the answers as correct; they're currently all marked as incorrect for this question. The correct answer is `はい、しました。` and I'll make sure to fix this with today's update.

**Comment by SethClydesdale** [comment]
This bug should now be corrected as of https://github.com/SethClydesdale/genki-study-resources/commit/cab952e87fee609011cf4291f73228c55b579d76! ✔️ 

Thanks again, and have a good day!

**Comment by drajguru** [comment]
Thanks!
