### ISSUE TITLE
Typo in Lesson 6 Culture Notes

### ISSUE THREAD

**Issue by Jirachi145** [SethClydesdale/genki-study-resources#112]
In this lesson, on the sixth question "The Japanese school year starts in _____ and ends in _____, with a long vacation in summer and two shorter breaks in winter and spring.", answer B has a typo. 
It reads "Aril and March", when it should in fact say "April and March"

Here's the link:
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-6/culture-1/

**Comment by SethClydesdale** [comment]
Hello @Jirachi145,

Thank you for reporting this typo! I'll send a fix for it online later today.

**Comment by SethClydesdale** [comment]
The typo should now be corrected! ✔️ 

Thanks again!
