### ISSUE TITLE
Wrong answer?

### ISSUE THREAD

**Issue by vgrigoriu** [SethClydesdale/genki-study-resources#113]
In [this exercise](https://github.com/SethClydesdale/genki-study-resources/blob/eadc7ddc9f47a7133250f05e961efad3cdd5eec3/lessons-3rd/lesson-1/grammar-3/index.html#L129-L131), is the marked answer correct? Isn't `ソラさんはにじゅうさいです。` correct because it has the `さい`?

**Comment by SethClydesdale** [comment]
Hello @vgrigoriu,

For twenty years old, it is more commonly written/read as [はたち](https://jisho.org/word/%E4%BA%8C%E5%8D%81%E6%AD%B3) (ha-ta-chi). It's one exception to keep note of when counting/pronouncing ages.

にじゅっさい／にじっさい _can_ be used and you'll be understood, but  はたち is the more preferable reading. The reason for this difference is related to 20 years of age being an important milestone in one's life.

**Comment by vgrigoriu** [comment]
Got it, thank you the explanation!

**Comment by vgrigoriu** [comment]
And apologies for not doing more research before posting 🙂

**Comment by SethClydesdale** [comment]
It's no problem, have a good day!
