### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by 641i130** [SethClydesdale/genki-study-resources#117]
Line 98 of this file https://github.com/SethClydesdale/genki-study-resources/edit/master/lessons/lesson-17/workbook-1/index.html
has a typo:
`'{トムさんの大家さんはとてもけちだそうです|トムさんのおおさんはとてもけちだそうです|answer}。'+`
should be
`'{トムさんの大家さんはとてもけちだそうです|トムさんのおおやさんはとてもけちだそうです|answer}。'+`

おおさん　->　おおやさん

**Comment by SethClydesdale** [comment]
Hello @641i130,

Thank you for reporting this typo! It should be corrected now. ✔️ 

Have a good day!
