### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by jahammond11** [SethClydesdale/genki-study-resources#12]
Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/vocab-5/
Issue: itsumo is spelt wrong. いっも -> いつも

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/grammar-2/
Issue: Question 3 with the verb あける is incorrectly spelt as おける in the question text.

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/workbook-4/
Issue: Question 10 'usually' is spelt wrong.
Issue: Question 11 is a bit confusing. The question is asking what Tanaka-san is going to do today, but his answer is in past tense? The answer provided also appears to be in present tense. Since past tense short forms isn't introduced until the lesson 9, might be better just to change Tanaka-san's answer to say he's going to do his part-time job today.

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/workbook-5/
Issue: Question 1's answer has a typo in it. The second part of the sentence for the hiragana answer should be おそくなりますから, not おすくなりますから.
Issue: Question 2 'forget' is spelt wrong.

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/workbook-1/
Issue: In the adjectives/nouns section, the past negative tense answer for きれい is incorrect. It should be きれいじゃなかった, not きらいじゃなかった.

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/workbook-3/
Issue: In question 6, Mary should be Mari here. I mistakenly thought it was referring to Mary-san, like most of the book has been up to this point, but it literally meant Mari-san.

By the way, thank you for the excellent resource! It's been very helpful to use alongside the actual books.

**Comment by SethClydesdale** [comment]
Hello @jahammond11,

Thanks a lot for reporting all these corrections! They should all be corrected now. ✔️ 

For the ～と言っていました workbook exercise, you're right to be confused! Tanaka's answer **should** be in the present tense at the time of his reply to the question. I must've got confused somehow when I was translating the answer back then, probably retaining the past-tense from the quotation. I changed his reply to "I will work part-time today."

Funny thing about the "Mari" typo: it's literally written as MA-RI in the workbook, but I wrote it as "Mary" in the question and "Mari" in the answer. I have no explanation for this tomfoolery other than I must've had Mary on the mind... _There's something about Mary_. haha

Glad to hear it's been helpful to you. Thanks again!

Have a good day.
