### ISSUE TITLE
Small spelling mistake in Tanabata story

### ISSUE THREAD

**Issue by NatsuOyasumi** [SethClydesdale/genki-study-resources#121]
Hello, I noticed a small spelling mistake in the Tanabata story. In the second box, in the last paragraph of the story (not counting the present-day culture notes) it says 二人の長いはかなうのです。I think it's supposed to be 願い・ねがい、and that is the word written in the vocab word bank underneath the story.

Here's the link to the Tanabata story: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/literacy-7/

Thank you! I love all the practices and quizzes you've made!

**Comment by SethClydesdale** [comment]
Hello @NatsuOyasumi,

Thank you for reporting this typo! It should be corrected now. ✔️ 

> Thank you! I love all the practices and quizzes you've made!

You're welcome! All the best on your studies. :)
