### ISSUE TITLE
Correct answers for https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/grammar-7/ are too easy to guess from sentence ending

### ISSUE THREAD

**Issue by malfet** [SethClydesdale/genki-study-resources#126]
There is only one answer out of 3 that ends with ~ない and it's always a correct answer.

**Comment by SethClydesdale** [comment]
Hello @malfet,

Thank you for bringing this to my attention; you're right, this is not ideal! I'll look into rewriting the incorrect answers with some different variations, possibly in the verb stem. I did add a fourth answer in the [3rd edition version](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-12/grammar-7/), however, I may also look into redoing those as well.

**Comment by SethClydesdale** [comment]
Hello again @malfet!

The incorrect answers should now be improved. If any issues, do let me know!
