### ISSUE TITLE
Genki 3rd Edition - 第6課 - Workbook: Listening Comprehension Error

### ISSUE THREAD

**Issue by CharlesLove** [SethClydesdale/genki-study-resources#133]
In part B of the 第6課 - Workbook: Listening Comprehension section, questions 1, 2, and 5 are incorrect.

- (1) the curtain is commanded to be opened, not closed. This should be "x".
- (2) the bathroom light is commanded to be turned off, not room light turned on. This should be "x".
- (5) the time is asked for London, not Japan. This should be "x".

**Comment by SethClydesdale** [comment]
Hello @CharlesLove,

For this particular problem you need only mark the things Robert says with "O". The things he does not say should be left blank.

Another actually reported this to me recently, so I will look into adding an additional sentence to clarify that point tomorrow. Perhaps:
> B: Robert is staying at a "smart hotel room" in Tokyo. Listen to his commands after "OK, My Room." Mark O for what he says, and leave what he does not say blank.

**Comment by SethClydesdale** [comment]
Hello again!

The description for section B in this exercise should now be updated.

```diff
-[OLD] Mark O for what he says.
+[NEW] Mark O for what he says, and leave blank what he doesn't say.
```

If anymore issues or questions, do let me know!

**Comment by CharlesLove** [comment]
Looks great! Makes it far more obvious that way.
