### ISSUE TITLE
Typo in Lesson 14 Practice: くれる/もらう

### ISSUE THREAD

**Issue by PaulWestphal** [SethClydesdale/genki-study-resources#135]
https://github.com/SethClydesdale/genki-study-resources/blob/master/lessons/lesson-14/grammar-5/index.html

Lines 9, 10, and 65 should say もらう, not もらる.

**Comment by SethClydesdale** [comment]
Hello @PaulWestphal, thank you for reporting this; I'll have it fixed by later today!

**Comment by SethClydesdale** [comment]
Hi again! As of https://github.com/SethClydesdale/genki-study-resources/commit/761d79fafa67885fbd306452e4415df1a9e2ef26 this typo should now be fixed! Somehow I missed it during the 3rd edition conversion (must be that troublesome autocorrect in our brains >_<), so it has been fixed there as well.

Thank you again! If any other issues, do let me know.

Have a great day (^_^)/
