### ISSUE TITLE
L17 Typo

### ISSUE THREAD

**Issue by vinxa** [SethClydesdale/genki-study-resources#139]
Hey just a quick typo report.

lesson-17 grammar-2, final question:
> ロバート：Japan in not dangerous.

**Comment by SethClydesdale** [comment]
Hello @vinxa,

Thank you very much for reporting this typo; I'll have it corrected soon!

**Comment by SethClydesdale** [comment]
Hi again! As of https://github.com/SethClydesdale/genki-study-resources/commit/7503472f97c5ea498779fb432e55db9f4f4cfd49, this typo should now be fixed!

If any other issues, feel free to let me know!
