### ISSUE TITLE
Lesson 15 Grammer Exercise 3 "Practice: Volitional Form + と思っています" does not allow honorific for カルロス.

### ISSUE THREAD

**Issue by PaulWestphal** [SethClydesdale/genki-study-resources#140]
カルロスさん should be valid, no?

**Comment by SethClydesdale** [comment]
Hello @PaulWestphal,

Indeed, the honorific for Carlos should be used here, but it appears I forgot to include it. I'll have this fixed up by later today.

Thanks for letting me know!

**Comment by SethClydesdale** [comment]
As of https://github.com/SethClydesdale/genki-study-resources/commit/c92ff7b19b4f41d2d01365b96d06bacc25719d88 this issue should now be fixed. Thanks again!
