### ISSUE TITLE
Lesson 11 Anki Cards

### ISSUE THREAD

**Issue by Paul-F-V** [SethClydesdale/genki-study-resources#142]
練習 (practice) is mistranslated as exercise (運動 or 演習).

**Comment by SethClydesdale** [comment]
Hello @Paul-F-V,

I believe that may be from the useful expressions where 練習 refers to an exercise, such as a quiz. It is one of the many meanings for it, but I think I will make some edits to further clarify that point.

Perhaps...
```
"exercise" --> "practice; (an) exercise"
```

I'll push these changes online tomorrow morning.

Thank you for bringing it to my attention.

**Comment by Paul-F-V** [comment]
Glad to help any way I can!

**Comment by SethClydesdale** [comment]
As of https://github.com/SethClydesdale/genki-study-resources/commit/4ac9c46c5352d8f1597b22ac93dca7992de0c67a, the definition for this word should now be updated.

If anymore issues, do let me know!
