### ISSUE TITLE
Lesson 4 Anki Cards - Days of the Month

### ISSUE THREAD

**Issue by Paul-F-V** [SethClydesdale/genki-study-resources#143]
All of the cards such as　じゅうににち　are translated into a standalone number like "12" when I think they should say something like 12th (day of the month).

**Comment by SethClydesdale** [comment]
Hello @Paul-F-V,

Thank you for the feedback! I do think that would be better than just a number alone. I'll look into updating this now.

**Comment by SethClydesdale** [comment]
As of https://github.com/SethClydesdale/genki-study-resources/commit/4ac9c46c5352d8f1597b22ac93dca7992de0c67a, the numbers should now display as "XX day of the month."

Thanks again!
