### ISSUE TITLE
Lesson 12 Anki Cards - 科

### ISSUE THREAD

**Issue by Paul-F-V** [SethClydesdale/genki-study-resources#145]
So while running through Lesson 12, I noticed that all of the types of medical specialists ended in 科 or "ka."  I paid this little mind until I got to 歯科, or dentist, when it struck me as odd because I recalled the word for dentist as "haisha," or "歯医者."  According to Wiktionary, the word 歯科 can mean dentistry or a dentist's office, but it doesn't translate as "dentist."  This got me thinking about the rest of the 科 words.  Would Japanese use the office and professional (not the profession, but the individual) interchangeably?

**Comment by SethClydesdale** [comment]
I think the usage may be akin to how we refer to it in English. Instead of saying we're going to the "dentist's office" we usually say we're going to the "dentist"; our destination being the office itself. I noticed 歯医者 and 目医者 are actually missing on these words for the exercise -- I'll make sure to add them in.

**Comment by Paul-F-V** [comment]
That's what I thought.  Though would it still be correct if someone said 「歯科です」or 「従妹は歯科です」?  Actually, plugging them into deepl does seem to work.

**Comment by SethClydesdale** [comment]
Doing a quick search of [歯科](https://www.google.com/search?q=%22%E7%A7%81%E3%81%AF%E6%AD%AF%E7%A7%91%E3%81%A7%E3%81%99%22) (3 hits) and [歯医者](https://www.google.com/search?q=%22%E7%A7%81%E3%81%AF%E6%AD%AF%E5%8C%BB%E8%80%85%E3%81%A7%E3%81%99%22) (25,800 hits). It seems like the latter is used more in this context. Even with the former though, considering the context, one should understand what you're saying.

**Comment by SethClydesdale** [comment]
Ah sorry, forgot to mention that the exercises/decks should be updated with the aforementioned changes!

Thanks again.
