### ISSUE TITLE
Wrong Answer

### ISSUE THREAD

**Issue by PercivallAkihiko** [SethClydesdale/genki-study-resources#146]
I continue to have wrong answer even if it right on question where there s  a dot or comma.

![image](https://user-images.githubusercontent.com/37913210/127676354-d9e4aee2-3595-4922-ac3b-ea1dbfdf83f3.png)

**Comment by SethClydesdale** [comment]
Hello @PercivallAkihiko,

「いええ」 should be 「いいえ」、with that it should be correct.

**Comment by PercivallAkihiko** [comment]
Sorry for the trouble then. I didn't pay attention.

**Comment by SethClydesdale** [comment]
It's no problem! Best of luck on your studies!
