### ISSUE TITLE
Typo L21 Workbook 4

### ISSUE THREAD

**Issue by vinxa** [SethClydesdale/genki-study-resources#147]
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-21/workbook-4/

> Question 8: Two tickets for Kabuki have been brought. Would you like to come with me?

'brought' should be 'bought'

**Comment by SethClydesdale** [comment]
Hello @vinxa, thank you for reporting this typo; it should be corrected now!

If any other issues, do not hesitate to let me know. Thank you again!
