### ISSUE TITLE
Lesson 16 Practice: ～てくれる／～てもらう Exercise 12 wrong furigana.

### ISSUE THREAD

**Issue by PaulWestphal** [SethClydesdale/genki-study-resources#149]
The kanji says 百円, but the furigana says せんえん. I think it should be ひゃくえん.

**Comment by SethClydesdale** [comment]
Hello @PaulWestphal, you're correct; it should be ひゃくえん! This typo should be corrected now, thank you for reporting it.

If any other issues, do not hesitate to let me know. Hope you have a good weekend!
