### ISSUE TITLE
Incorrect wrong answer detection [3rdED;L4;WB8;Q3]

### ISSUE THREAD

**Issue by CyberSamurai** [SethClydesdale/genki-study-resources#152]
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-4/workbook-8/

Question number 3; written-type.   It's stating i have a wrong answer but by all means i can tell my answer is identical to the suggested answer.  　It wasn't until I pasted the answer in here that i realized the issue.  It seems that most answer lines provide a built in period while this question does not.

This is copy pasted directly from the page, my answer on top and the suggested answer underneath

はい、犬がいます。名前はポチです
はい、犬がいます。名前はポチです。

After going back and adding a period it accepted the answer.   I have run into this a few times before where my answer was identical but was still being counted wrong; however, I never spotted the missing period until opening this bug report.

Is the missing period just something we're supposed to be looking for when typing the answers or is that a mistake?

**Comment by SethClydesdale** [comment]
Hello @CyberSamurai,

Normally for problems that contain multiple sentences, it falls upon the user to include the proper punctuation. I can see how it is a problem, however, so I will take a look at the answer checker to see if I can strip punctuation, specifically on the end.

**Comment by GregMorford** [comment]
Yeah that makes sense.  Your approach to the answer checker sounds better than the one-off fix i submitted in a pull request.  I just fixed that one answer line to include the period at the end.

**Comment by SethClydesdale** [comment]
https://github.com/SethClydesdale/genki-study-resources/commit/1bcde84e53602f2c5c992c499310db2befcfb088 should have updated the answer check to now ignore punctuation (。 and 、specifically) when checking answers.

If the issue is still persisting or something else crops up, do let me know!
