### ISSUE TITLE
PWA (Progressive Web App)

### ISSUE THREAD

**Issue by AlexApps99** [SethClydesdale/genki-study-resources#154]
Making this site a PWA would be useful for two reasons:
- using the site offline without any setup/server
- adding app to homescreen for mobile devices

If this sounds good, I could probably put together a PR at some point.

Great resource so far :+1:

**Comment by AlexApps99** [comment]
Are there any sources for the icons (`genki.png` and `genki-thumb.png`) that are larger? Chrome requires icons of `512x512` for the splash screen, and `192x192` for `apple-touch-icon`.

As well as this, how do I edit all the pages' HTML at once? I couldn't find any templating system, so I assume I just find and replace across all files?

**Comment by SethClydesdale** [comment]
Hello @AlexApps99!

That does sound nice! It seems like I lost the editable version of those icons, but I was able to recreate a larger variant that you can use.

![genki-alpha](https://user-images.githubusercontent.com/10122549/142648097-743db28b-e4bc-49a8-96e4-5a7b74cfcaf1.png)

The text used is Meiryo UI btw.

Ah yes, everything is setup as static HTML (without templates) so the repo could be downloaded and used offline as is, with zero setup. But for editing all pages at once, I used https://github.com/zzzprojects/findandreplace which is pretty handy.

**Comment by AlexApps99** [comment]
How do I edit CSS/JS files? Need to use the same minifier so git diffs aren't too big

**Comment by AlexApps99** [comment]
I have a prototype up at <https://yttriferous.dev/genki-study-resources> that works, but is still rough around the edges.
It automatically downloads 100MB of content when you first connect, without any prompt or warning.
Some of the pages also have broken CSS. I'm not sure if it's eligible to be installed as an app on homescreens yet, either.
Before I make a PR, I will be sure to address those issues and make the feature a lot nicer to use.

**Comment by AlexApps99** [comment]
![Screenshot_20211120-211944_Chrome.jpg](https://user-images.githubusercontent.com/30854646/142719633-857fd1f8-b868-4b29-be71-73f27526bf32.jpg)
![Screenshot_20211120-211910_Chrome.jpg](https://user-images.githubusercontent.com/30854646/142719641-1f91c4b9-0c3c-41f3-a91d-c7825bdc815a.jpg)

**Comment by SethClydesdale** [comment]
Nice work, it looks good so far!

For minifying JS/CSS I used [clean-css](https://github.com/clean-css/clean-css) and [Uglify JS 3](https://github.com/mishoo/UglifyJS) in a [minifier extension](https://github.com/abagshaw/brackets-minifier) for brackets.

**Comment by AlexApps99** [comment]
Sorry for the pause, I'm on holiday right now using my initial work for off grid studying and it's going well. Before I create a PR, I want to add a setting to the settings menu so it will only be downloaded when asked, and I want to add messages about the removal of voice clips stroke order etc (and maybe an option to download it)

Once I get back I'll try to sort that all out.

Thanks for the great resource

**Comment by SethClydesdale** [comment]
Hey! Thanks for the update. It's no rush, take your time and enjoy the holidays! :)

**Comment by AlexApps99** [comment]
Sorry, I've put this off too long and I don't think it's likely I'll end up finishing it.
Thanks for understanding
