### ISSUE TITLE
Dictionary かんごし missing reference 

### ISSUE THREAD

**Issue by AndreaMinerva** [SethClydesdale/genki-study-resources#155]
In lesson 1 the word かんごし (nurse) is present but not correctly reported in vocabulary index 

![image](https://user-images.githubusercontent.com/5547588/143225039-93acad10-f3a0-429b-9cce-9177dfcddfc1.png)

**Comment by SethClydesdale** [comment]
Hello @AndreaMinerva,

Thank you for reporting this! It should be updated with the reference to L1 now.

If any other issues, don't hesitate to let me know. Have a good day!
