### ISSUE TITLE
Mistake in Genki I page 25. A, B & C

### ISSUE THREAD

**Issue by lambdacore12** [SethClydesdale/genki-study-resources#158]
Hello. Thank you very much for your efforts. May God reward you properly.
I'm contacting you regarding an issue in "Genki I page 25. A, B & C".
In exercice A, the audio has no mention of chocolate, and when I click on the audio for chocolate, it just takes me to 00:07.
I also think the order for the objects is not correct, but I think that is intentional for learning purposes, right?

![image](https://user-images.githubusercontent.com/37704802/145155877-049512a6-7730-43bb-91ea-dea81d034baa.png)

**Comment by SethClydesdale** [comment]
Hello @lambdacore12!

Yes, it is intentional for learning purposes. Since chocolate is not mentioned, it can be filled in with a question mark.
