### ISSUE TITLE
Spelling mistake on Genki II 3rd edition page 41

### ISSUE THREAD

**Issue by Loopsyded** [SethClydesdale/genki-study-resources#161]
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-16/workbook-7/ 

Question 3:
"You could no go to your friend's birthday party." 

Should be "You could not go to your friend's birthday party."

**Comment by SethClydesdale** [comment]
Hello @Loopsyded, thank you for reporting this typo!

It should be corrected now. If you notice any other mistakes or bugs do not hesitate to let me know. Thanks again!
