### ISSUE TITLE
Show Furigana Button is non-responsive on Lesson 9 / Exercise 10 

### ISSUE THREAD

**Issue by justin** [SethClydesdale/genki-study-resources#164]
**Exercise**: [Practice: ～から - Lesson 9](https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/grammar-10/)
**Environment**: macOS 12.3.1 on both Safari 15.4 and Microsoft Edge / Chromium 100.0.1185.50

### Steps to Reproduce

1. Open [Practice: ～から - Lesson 9](https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/grammar-10/) in your browser. 
2. Ensure you are using the drag-and-drop experience. 
3. Click on the "Show Furigana" button and notice nothing changes. 
4. Click on the "Hide Furigana" button and notice nothing changes. 

### Additional Info

Looking in the browser console doesn't show any errors being thrown, so it wasn't super obvious what is going on. 

Of note, it seems like the drag & drop behavior will sometimes fail to acknowledge a release of an answer in one of the answer blocks. That may be by design if its a wrong answer though? If that's indeed a bug, I can file a separate ticket if you like.

Thanks!

**Comment by SethClydesdale** [comment]
https://github.com/SethClydesdale/genki-study-resources/commit/89c65d632026ef8736edc6593fa5e3edc5f5cc53 should have upgraded the exercise to a written one with furigana support. If any issues, let me know!
