### ISSUE TITLE
Multiple answer options

### ISSUE THREAD

**Issue by justfeedbacktoo** [SethClydesdale/genki-study-resources#167]
Is there a way to give multiple options for multiple sets of words in answers like below instead of making a compete sentence for every combination?

(私/わたし)は(日本語/にほんご)の(先生/せんせい)です

**Comment by SethClydesdale** [comment]
Hello @justfeedbacktoo!

For multiple combinations, I used [Genki.getAlts](https://github.com/SethClydesdale/genki-study-resources/blob/02dddff74e24c07e6308bdfb15846fd05f082527/resources/javascript/genki.js#L2379) which returns a list of alternative answers based on the provided combinations. General syntax looks something like this.
```javascript
'{今日、図書館に行った|きょう、としょかんにいった|' + Genki.getAlts('{今日}、{図書館}に行{った}', 'きょう|としょかん|きました') + 'answer}'
```

In some rare instances you may need to use more than one of these, but they can be chained like so.
```javascript
'{answer1|answer2|' + Genki.getAlts('', '|') + Genki.getAlts('', '|') + 'answer}'
```

On page, you can add `?debug` to the end of the URL to return a list of all the alternative answers in the web console.

![Screenshot 2022-06-06 113050](https://user-images.githubusercontent.com/10122549/172193862-a684fc6f-97f5-40e2-8b08-87a663841849.png)


If any questions let me know.
