### ISSUE TITLE
Mixed hiragana and kanji answer

### ISSUE THREAD

**Issue by jon-a-g** [SethClydesdale/genki-study-resources#171]
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-3/workbook-3/

Description: Question 10 counts as incorrect if you don't use "家" for "うち/いえ" while usinh the kanji for 日本語 and 話します. It threw me because the textbook only uses 家 for いえ.

Steps to replicate: Enter "私はうちで日本語を話します" as the answer to lesson 3, workbook 3, question 10. It should come up as incorrect. But if you enter "私は家で日本語を話します" then it counts as correct.

Browser: Chrome 104.0.5112.97

Operating system: Android 13

Online or offline: Online

**Comment by SethClydesdale** [comment]
Hello @jon-a-g, thanks for reporting this! It looks like there was a typo in one of the alternate kana lists (`うち|いえ|にほんご|はな` instead of `わたし|うち|にほんご|はな`). It should be corrected now!
