### ISSUE TITLE
Furigana not showing up. 

### ISSUE THREAD

**Issue by sunsetworld** [SethClydesdale/genki-study-resources#174]
Hello.

Furigana is not showing up for Genki Study Resources even with Furigana set to ON.

![image](https://user-images.githubusercontent.com/68568350/193413074-4396cc6f-bb27-4fca-b924-ebf1f70c0975.png)
![image](https://user-images.githubusercontent.com/68568350/193413086-9626a77b-fb05-4ff4-9d62-216b07d957aa.png)

**Comment by SethClydesdale** [comment]
Hello @sunsetworld!

From what I can tell, it appears you're using the 2nd edition resources, correct? During the first development cycle (for the 2nd Ed.) furigana was partially supported, so not all exercises contain it.

As a solution, you can use the built in quick dictionary or the [Yomi-chan](https://chrome.google.com/webstore/detail/yomichan/ogmnaimimemjmbakcfefmnahgdfhfami?hl=en-US) extension to help make looking up readings/meanings easier. Additionally, you can use the [3rd edition resources](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/) which have full furigana support. There's only some minor differences from the 2nd edition contents, so I recommend giving it a try if the above solutions aren't favorable.
