### ISSUE TITLE
Workbook Correct Answer Errors

### ISSUE THREAD

**Issue by micwaab** [SethClydesdale/genki-study-resources#175]
Hello,

I have been using the Genki modules on GitHub for a few weeks. Until today, everything was working well. However, when I completed workbook p 127 today and checked the answers there was an error.

Specifically, while all I made all correct answers, many were marked incorrect. Furthermore, the Genki correct answer (shown in green below) displayed answers matching all of those marked incorrect on my input.

See screenshot.

Any ideas what's going on here?

![CleanShot 2022-10-02 at 10 03 02@2x](https://user-images.githubusercontent.com/47571490/193461117-89c7686c-00ac-47ab-9547-2840c40a480b.png)

**Comment by SethClydesdale** [comment]
Hello @micwaab!

Just to confirm, did you input a zero (0) or circle (O) in those fields? (the latter is expected) As for the hiragana, the small characters must be written, which you can do by prefixing the kana with an "x" as shown below:
- xyo = ょ
- xtsu = っ

**Comment by micwaab** [comment]
Thank you for the quick reply!

I understand now how to format my answer input on your Genki resourses.

Best,

M
