### ISSUE TITLE
Typo in chapter 17

### ISSUE THREAD

**Issue by ClausLJ** [SethClydesdale/genki-study-resources#18]
Hi

On page
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-17/literacy-7/

In the poem, the second line: 雲を**教**えて should be  雲を**数**えて

Br
Claus

**Comment by ClausLJ** [comment]
Another one on the same page:

a few lines after the poem（305ページの写真）should just be （写真）

Br
Claus

**Comment by SethClydesdale** [comment]
Hello @ClausLJ,

Thank you for the report! These issues should be corrected now. ✔️ 

> a few lines after the poem（305ページの写真）should just be （写真）

This was a reference to the image on page 305 of the textbook, but I think removing it is a good idea. I went ahead and updated the exercise with the referenced image which should provide greater clarity.

Thanks again for your help.

Have a good day.
