### ISSUE TITLE
Edition 2 - Lesson 3 Practice Verb Conjugation Typo

### ISSUE THREAD

**Issue by gabriellecozart** [SethClydesdale/genki-study-resources#183]
Typo in:
"Change the verbs into ～masu and ～mare."

Should be:
"Change the verbs into ～masu and ～masen"

But better (fits the textbook): 
"Change the verbs into ～ます and ～ません."

**Comment by gabriellecozart** [comment]
Aside from this, the whole quiz for this lesson seems strange. May need to revisit the possible question/answer combos

**Comment by SethClydesdale** [comment]
Hello @gabriellecozart! I took a quick look and everything appears to be in order on my end.

![Screenshot 2023-01-01 094826](https://user-images.githubusercontent.com/10122549/210174777-42a6cc84-7b05-458a-ad6d-7a3a56542644.png)

Just to confirm, do you perhaps have an extension enabled that's auto-translating the page? That could explain why it's displaying a strange romaji variant over the kana.

**Comment by gabriellecozart** [comment]
Hmmm interesting. I worked on the entire chapter 3 section yesterday and this was the only section that was giving me issues. I will check out the auto translate and that section again and see if there are issues. 

I'll grab any screenshots if I see them again. What's weird is it was also trying to have me conjugate the "verb" frog as well and there would be duplicate answers. All the answer choices were also in English.

**Comment by gabriellecozart** [comment]
Hmm it appears to be as expected now. Very strange

**Comment by SethClydesdale** [comment]
It could be something similar to these issues: #170 or #163

If you do figure out the cause, let me know!
