### ISSUE TITLE
Weird font?

### ISSUE THREAD

**Issue by xristosv1234** [SethClydesdale/genki-study-resources#188]
So I opened the site after about a month of not using it, and imediately I thought the was somethings wrong with the font. It doesn't look wrong, maybe a bit tough to read, but I think it used to be smooth. 

I tried edge and chrome. The font is normal on my phone. 

Please excuse me if I am an idiot and it was always like this. This is an amazing resource but I can't focus without thinking about it. 
Screenshot: https://imgur.com/a/9977o2h

If it was always like this, may I suggest a replacement? Sorry if I am being arrogant :(

**Comment by SethClydesdale** [comment]
Hello @xristosv1234!

From the looks of it, I believe it's falling back to MS PGothic in the font stack. Normally, if it's installed, Meiryo would be in use which cleanly supports both Roman and Japanese characters. I've attached an archive with Meiryo's fonts below that you can install.

[Meiryo.zip](https://github.com/SethClydesdale/genki-study-resources/files/10519634/Meiryo.zip)

If the issue still persists after installing them, let me know 👍

**Comment by xristosv1234** [comment]
Thanks for replying so quickly. It seems that this did the trick, I would have never imagined this on my own. Its probably because I hadn't installed the japanese language pack. 

Thank you so much for everything, the website is a lifesaver <3

**Comment by SethClydesdale** [comment]
You're welcome! And yeah, installing the Japanese language pack should also install Meiryo, so that's probably it. I'd definitely recommend installing it, since it'll come in handy for a lot of Japanese related things, especially the IME.

All the best on your studies! 頑張れー！
