### ISSUE TITLE
第5課 - Workbook: Adjective Conjugation (Present Tense) - Dictionary form of "good" incorrect

### ISSUE THREAD

**Issue by TaakoMagnusen** [SethClydesdale/genki-study-resources#189]
第5課 - Workbook: Adjective Conjugation (Present Tense)
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/workbook-1/

For い-adjectives, number 6. Good i put 良い「よい」 as the dictionary form and it says incorrect, marking the correct answer as いい.

いい is only used as the present tense form, it is not the dictionary form.
https://www.tanoshiijapanese.com/dictionary/conjugation_details.cfm?entry_id=58486

<img width="987" alt="Screenshot 2023-01-28 at 9 18 53 AM" src="https://user-images.githubusercontent.com/39819109/215280007-f36ddae3-2bb5-4f54-9310-f1fa7566378c.png">

**Comment by TaakoMagnusen** [comment]
Looks like there are other issue using the kanji for 良 as well.

In the next exercise i was marked wrong for using the kanji instead of よ
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/workbook-2/


<img width="471" alt="Screenshot 2023-01-28 at 9 27 32 AM" src="https://user-
images.githubusercontent.com/39819109/215281760-515f9bff-db1c-41f7-8cff-86d1d2422f2a.png">

I've seen similar issues using 綺麗 「きれい」, the website wont let me use the kanji anywhere, i always have to use the hiragana or im marked wrong

**Comment by TaakoMagnusen** [comment]
documenting more instances where the kanji isnt accepted
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/workbook-3/

<img width="1242" alt="Screenshot 2023-01-28 at 9 42 55 AM" src="https://user-images.githubusercontent.com/39819109/215282467-2c7fc1ce-0892-49be-bec1-731c4a749c4e.png">

**Comment by SethClydesdale** [comment]
Hello @TaakoMagnusen!

Thank you for informing me of this! Initially when developing these resources, I only included the hiragana versions of these words, since the kanji for them wasn't used/taught in the textbooks. I'll look into implementing the kanji variations of these words where possible (including #190 & #187) later on once I've finished working on Tobira, as it'll require quite a bit of time to do.

**Comment by TaakoMagnusen** [comment]
Thanks for the response!

Just wanted to call out that this has been a life changing resource for my self studying.

**Comment by SethClydesdale** [comment]
Hello again @TaakoMagnusen!

The following alternatives should now be supported:

- よい／良い for いい
- 良かった for よかった
- よく for various instances of 良く (such as 良くない)

If you notice anymore issues like this one please feel free to open a new issue. Thanks again!
