### ISSUE TITLE
Chapter 5 practice and workbook don't allow for use of 綺麗「きれい」(beautiful, clean). Must use hiragana or marked wrong

### ISSUE THREAD

**Issue by TaakoMagnusen** [SethClydesdale/genki-study-resources#190]
Pretty much title is explanatory. On every chapter 5 practice and workbook involving きれい（な）if i dont enter the hiragana it's marked wrong even though the kanji should be acceptable （綺麗）.

**Comment by SethClydesdale** [comment]
Hello @TaakoMagnusen!

Just letting you know that I pushed an update today that enables the usage of 綺麗 in place of きれい. If you notice anywhere that you still can't use the kanji as an answer for this word, please let me know. Thanks again!
