### ISSUE TITLE
Contribution Kanji Decks

### ISSUE THREAD

**Issue by Zakkaruu** [SethClydesdale/genki-study-resources#192]
Hi,

It might seem odd to provide a contribution as an issue, but I am no where near a developer and have never done a pull request. I wanted to contribute kanji decks using a modified version of the anki_decks_maker.py file and other resources in your project.

This script is basically a copy, but it changes the filter_regex, limits the folder search to literacy-1 and literacy-2 for each lesson (where kanji readings and meanings are), and uses some new regex matching to extract the information.

The cards have a few new fields and I have changed the formatting to my preference, which may or may not be what everyone else likes. Essentially it shows the kanji and readings, but you can hover underneath the kanji to show the meaning on the answer card.. It does this using dark mode colors to hide text, but I have done nothing with the light/dark mode logic to hide in light mode as well.

Examples:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20016567/216733887-2822e6d9-e8d2-4739-88ef-5e6cee2b26d3.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20016567/216733928-cfe3b940-6622-4867-b38e-a8f36648fde8.png">
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20016567/216733939-ed8dceb0-f3d3-4c8f-aa37-050ba046f643.png">

So, I'm basically dropping off the files and giving permission to take the modified work. Attached are the pre-built decks. I'm also only a novice 日本語 student, so _I believe_ they are correct, but honestly I'm only into Genki I Chapter 8 myself. I've done spot checks to verify it matches with the website, but it is an extremely small portion of them.

[kanji.zip](https://github.com/SethClydesdale/genki-study-resources/files/10593486/kanji.zip)
[anki_kanji_decks.py.zip](https://github.com/SethClydesdale/genki-study-resources/files/10593492/anki_kanji_decks.py.zip)

**Comment by SethClydesdale** [comment]
Hello @Zakkaruu!

I took a quick look over and everything looks good! I think this'll be a great addition, so I'll look into implementing it into the repository and site when I get the chance. Thank you for taking the time to put this together!

**Comment by SethClydesdale** [comment]
Hi again! As of https://github.com/SethClydesdale/genki-study-resources/commit/8dde7222c9392d23bf0d3359316dd014d64cd09a the kanji decks have been added to the repo! They're also available online here:
https://sethclydesdale.github.io/genki-study-resources/help/anki-decks/#kanji-decks

Thanks again!
