### ISSUE TITLE
Immediate Feedback

### ISSUE THREAD

**Issue by TayeBeckford** [SethClydesdale/genki-study-resources#195]
I noticed that with most of the practice you have to wait until after you've answered a set of questions to get feedback. I was wondering if you could create mode where there's immediate feedback after every question. I find this a bit better for my learning as I can progressively learn the patterns rather than kind of guess and have to wait until the end to see how to do it right. Also thank you for this amazing resource. Just found it today and I already love it! Thanks!

**Comment by SethClydesdale** [comment]
Hello @TayeBeckford, thank you for the suggestion and you're welcome as well! This should be possible to implement, though would require reworking a few things and then adding a new option so students can switch between these modes. I'll write this down on my todo list to investigate for when I'm not too busy 👍

**Comment by SethClydesdale** [comment]
Hello again @TayeBeckford!

Now that I've finished up work on the Tobira resources, I've had some time to work on implementing this feature. It should be available now on the website under the settings manager. You can choose between two modes:

- Classic: only shows your answers at the end of the quiz. (default)
- Instant: shows your answers immediately as you progress through the quiz. A "next" button displays underneath the options in this mode after answering.

![Screenshot 2023-03-04 113120](https://user-images.githubusercontent.com/10122549/222918175-82eec685-7381-453e-a9d3-c0555a186b04.png)

If any issues occur or if you have any questions, please let me know. Thank you again for this suggestion 👍
