### ISSUE TITLE
Workbook: Noun も・Noun じゃないです Correct answer not accepted

### ISSUE THREAD

**Issue by CaptNoBeard422** [SethClydesdale/genki-study-resources#198]
Link: https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-2/workbook-5/ 

Question number 2 asks to translate the following:  Ms. Tanaka is 20 years old. Mr. Yoshida is 20 years old, too.
I answered with: たなかさんはにじゅっさいです (tanaka-san wa nijussai desu.)。 よしださんもにじゅっさいです (yoshida-san mo nujussai desu.)。

This was marked incorrect since I did not use "hatachi" for 20 years old, even though (nijussai) also means 20 years old, as shown in Genki I 3rd edition, Lesson 1, page 47.

**Comment by SethClydesdale** [comment]
Hello @CaptNoBeard422! 

I believe はたち was the answers given by the workbook for this exercise, since it's more natural, however both _are_ applicable readings for 二十歳 so I'll look into adding にじゅっさい／にじっさい as answer alternatives with today's update.

**Comment by SethClydesdale** [comment]
Should be updated now! If anymore issues, please feel free to contact me 👍

**Comment by CaptNoBeard422** [comment]
Thank you! and thank you for this tool.  It is so very useful!
