### ISSUE TITLE
第8課 - Workbook: Translate the Sentences

### ISSUE THREAD

**Issue by gcfreak** [SethClydesdale/genki-study-resources#2]
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/literacy-wb-7/

Question 1 reads: I read a newspaper on a train.
The answer reads: 私は電車で新聞を飲みます (わたしはでんしゃでしんぶんをのみます)
I drink newspaper on the train.
![capture](https://user-images.githubusercontent.com/47119443/51857899-43659a80-22e8-11e9-800a-97f065658dfa.PNG)

The correct answer should be: 私は電車で新聞を読みます
(わたしはでんしゃでしんぶんをよみます)
It can also be past tense. "Read" written in English is unclear on tense.

**Comment by SethClydesdale** [comment]
@gcfreak thanks for the report, I'll look into correcting this ASAP ! 👍 

You're correct that the tense IS a bit unclear. I might put a note there indicating the sentence should be written using the present tense.
