### ISSUE TITLE
Chapter 17 Typo

### ISSUE THREAD

**Issue by ClausLJ** [SethClydesdale/genki-study-resources#20]
On page

https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-17/literacy-7/

The name of Yoko and John's son is spelled **ジ**ョーン and should be **シ**ョーン.

Thanks for the great study resources!

Br
Claus

**Comment by SethClydesdale** [comment]
Hi @ClausLJ,

Thanks for reporting this typo! It should be corrected now. ✔️ 

You're welcome, thanks again for your help! 👍 

Have a great day.
