### ISSUE TITLE
Incorrect Answer for 第1課 - Practice: Noun の Noun 3 - Question 6

### ISSUE THREAD

**Issue by caball01** [SethClydesdale/genki-study-resources#201]
Question 6, asking for Sora's major, marks コンピューター wrong, and thinks the correct answer should be コンプューター (difference in the third character). The first matches the text in the table.

Link to the page that contains the mistake(s): https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-1/grammar-9/
Erroneous content: Question 6 answer コンプューター
Correction of the content: should be コンピューター

**Comment by SethClydesdale** [comment]
Hello @caball01!

I just took a look over the page, however, I couldn't find any instances of コンプューター, even when checking the files internally. If possible, could you get a screenshot of this so I could investigate further?

**Comment by caball01** [comment]
No - I just redid the exercise, and it was marked correct this time. While I did my best to determine that it was an error before trying to report it, I think it's safe to assume I confused my submitted answer with the corrected answer when comparing to the value in the table at the top of the page.

Thanks for taking a look at it.
________________________________

**Comment by SethClydesdale** [comment]
No problem! Thanks for clarifying 👍 

If you have any other problems or encounter a bug, feel free to contact me anytime by opening a new issue.
