### ISSUE TITLE
advice:change the method of show a multiple choiceresult is correct or not 

### ISSUE THREAD

**Issue by Oshibuki** [SethClydesdale/genki-study-resources#203]
when I use it on my android phone, the outline color is too hard to be recognized, so I cant konw which iscorrect or wrong.
Maybe using background color is better?

**Comment by SethClydesdale** [comment]
Hello @Oshibuki!

I can see what you mean, so I went ahead and upped the size of the outline as you can see below.

![Screenshot 2023-04-22 100548](https://user-images.githubusercontent.com/10122549/233789655-274ae271-5cfa-4c8e-984c-e3ee57660fd8.png)

If it is still difficult to see, please let me know.

**Comment by Oshibuki** [comment]
thanks a lot!
now it is more friendly
![IMG_20230422_232307.jpg](https://user-images.githubusercontent.com/20656904/233793096-c7b59537-7eb2-4643-8a0a-7a528db2cfeb.jpg)

**Comment by SethClydesdale** [comment]
You're very welcome! And thank you for the suggestion!

If you ever have anymore suggestions or questions, feel free to contact me anytime by opening a new issue 👍 
日本語の勉強頑張って下さいね٩( 'ω' )و
