### ISSUE TITLE
Lesson 1 Vocabulary 2 - Correct answer not accepted (Japan)

### ISSUE THREAD

**Issue by eibex** [SethClydesdale/genki-study-resources#204]
I just stumbled upon this repo and it looks amazing.

While I was testing it out I noticed that in Lesson 1 Vocabulary 2 matching にほん with Japan gives an error when it is correct.

**Comment by eibex** [comment]
Just noticed that dropping an answer by mistake will mark it as wrong even if you fix it before completing the exercise.

**Comment by SethClydesdale** [comment]
Ah yes, it logs how many times you dropped the wrong word so that you can focus your reviews on those words.
