### ISSUE TITLE
[Error] Workbook: Noun の Noun (p.18; I & II) (3rd Edition)

### ISSUE THREAD

**Issue by pksieminski** [SethClydesdale/genki-study-resources#207]
Hi!
I own workbook for Genki 1 (3rd Edition) and noticed that one of questions for Lesson 1 differs.

I.1: English-language teacher

Should be:
I.1: Japanese-language teacher

I think this makes sense if they changed it in 3rd Edition, as at Lesson 1 you aren't supposed to know Katakana yet, and "English" should be written using Katakana not Hiragana?

**Comment by SethClydesdale** [comment]
Hello!

I check both my 3rd and 2nd edition workbooks and they both list this problem as "English-language teacher." Perhaps this was revised later? In any case, English (language) is natively spelt as えいご (英語), which is comprised of the kanji for England/English + Language/Speech/Word.

**Comment by pksieminski** [comment]
Totally my bad about "English" being written in hiragana. You are ofcourse right.

And as you said, maybe they revised it later. I will close this issue then!

![IMG_3005](https://github.com/SethClydesdale/genki-study-resources/assets/57523979/708b3dac-a73c-4473-9fcb-6f06aea20f6c)
