### ISSUE TITLE
第6課 - Practice: ～から - Question 6 has the wrong translation

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#209]
<img width="480" alt="image" src="https://github.com/SethClydesdale/genki-study-resources/assets/2729079/24e73a47-21f6-498b-9979-1295cee0d401">

My understanding is that から should convey the reason for the preceding sentence. But why does it make sense to borrow a textbook from your friend, _because_ you studied? If you already studied, why would you need to borrow a textbook at all?

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory!

You're right that the answer here doesn't fit at all. Looking at the context, perhaps the follow up reason for this problem should be changed to something like this: 私の教科書を忘れましたから (because I forgot my textbook)

**Comment by SethClydesdale** [comment]
Should be updated with the answer I suggested in my prior response! If you run into anything else like this feel free to contact me again 👍
