### ISSUE TITLE
第7課 - Practice: Adjective/Noun Te-forms 

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#210]
Hey Seth,

Is the answer here wrong? 背が高い is the adjective IIUC, which conjugates to 背が高くて in the て-form.

<img width="656" alt="image" src="https://github.com/SethClydesdale/genki-study-resources/assets/2729079/08fed2ef-5a34-4b2d-be50-fc9a422b654d">

**Comment by yangmillstheory** [comment]
Or is the adjective really 高い？

**Comment by yangmillstheory** [comment]
> Or is the adjective really 高い？

Yep, I think this is it. So I misunderstood things. Sorry for the noise!

**Comment by SethClydesdale** [comment]
No worries! But yes, that's correct, as 高い is used to generally refer to how high/tall something is, such as a mountain or building. 背が高い on the other hand is used to refer to a person's stature. A good way to remember the difference is that 背 has a few meanings related to people, such as back/spine and height/stature.

**Comment by yangmillstheory** [comment]
Thanks for clarifying!
