### ISSUE TITLE
Character Mistake in 5-III-A-4 Answer in 3rd Edition Resource

### ISSUE THREAD

**Issue by mokahless** [SethClydesdale/genki-study-resources#212]
https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/grammar-9/

Number 4. is いそがしいひ**た**ですね. It should be いそがしいひ**と**ですね. For the kana portion answer. Same with 5.

**Comment by SethClydesdale** [comment]
Hello @mokahless!

Thank you for reporting this typo, it should be corrected now!
