### ISSUE TITLE
Drag and drop sometimes incorrectly marks answers as incorrect 

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#213]
Example:

<img width="372" alt="image" src="https://github.com/SethClydesdale/genki-study-resources/assets/2729079/bebba9a9-517e-41ba-b63a-8da190913f15">

I'm fairly sure that "to be late" is correct here; here's the [Kanji lookup](https://jisho.org/search/%E9%81%85%E3%81%8F) on Jisho.

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory! 

Yes, that answer appears to be correct! As for why it's marked wrong, it could possibly be related to a report I received awhile back where dragging an answer will sometimes prematurely drop it into the wrong zone thus incrementing the error count for that problem. Unfortunately I haven't been able to reproduce the problem on my end, so if you (or anybody else) figures out the steps to reproduce it please let me know!
