### ISSUE TITLE
Keybinding for Hide / Show Furigana

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#214]
It'd be nice to not have to scroll down to Hide / Show Furigana. I prefer to have it hidden by default, and quickly show it when I want it, then make it go away.

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory!

You can toggle Furigana on or off by pressing CTRL+ALT+F, there's also a few more shortcuts that you can find [here](https://github.com/SethClydesdale/genki-study-resources#keyboard-shortcuts). If you have any other issues or questions, let me know!

**Comment by yangmillstheory** [comment]
Thanks Seth, please feel free to close this issue.

**Comment by yangmillstheory** [comment]
Are the keyboard shortcuts expected to work for Mac keyboards as well?

**Comment by SethClydesdale** [comment]
They should, though I haven't tested since I don't own one. I believe the shortcut would be CMD+OPT+F however. If it doesn't work, let me know and I'll see about fixing it.

**Comment by yangmillstheory** [comment]
I just found out that Command + Option + F is "search the web" in the Chrome browser:

<img width="680" alt="Screenshot 2023-08-06 at 19 35 07" src="https://github.com/SethClydesdale/genki-study-resources/assets/2729079/ce4c0d57-9461-4ee8-99ba-358cdfa8c2eb">

I can confirm that that's what those keybindings do for me. There might be other shortcuts [here](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop) that take precedence.

**Comment by SethClydesdale** [comment]
Thanks for letting me know! I'll look into this when I get the chance to see if I can fix this.

**Comment by SethClydesdale** [comment]
Hello again @yangmillstheory! I've made some minor adjustments to the shortcut handler. When you have a chance, please let me know if the CMD+OPT+F shortcut is working properly or if it's still initiating a search. Thanks!

**Comment by yangmillstheory** [comment]
Unfortunately it's still initiating a search. Let me know how I can help
further.

**Comment by SethClydesdale** [comment]
Hmm... I'll have to try looking for another solution in that case.

**Comment by yangmillstheory** [comment]
How about a different key binding? One that doesn't conflict with Chrome
default keybindings.

**Comment by SethClydesdale** [comment]
That's what I was thinking. I'll probably setup alternate shortcut keys for mac keyboards. I'll let you know when I implement this change 👍

**Comment by SethClydesdale** [comment]
Hello again, @yangmillstheory! I apologize for the late reply, I was taking a break since I haven't been feeling well lately.

I went and updated the key handler for the shortcuts to CMD+SHIFT+[KEY] for mac. Let me know if CMD+SHIFT+F works properly to toggle furigana or not.

**Comment by yangmillstheory** [comment]
ありがとうございます！
