### ISSUE TITLE
第10課 - Practice: Adjective + なる 2 - incorrect answer

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#218]
Hey,

For Problem 1, we have:

>エアコンをつけたから、すぐ暖かくなりますよ。

Is this correct? AFAICT the translation for this is "I turned _on_ the air conditioner, so it got warm immediately."

Suggestion: use the verb 消す in the first part of the sentence to make this correct.

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory!

I believe this is correct. In Japan, エアコン come with both cooling and heating functions.

**Comment by yangmillstheory** [comment]
そうですか。わかりました。
