### ISSUE TITLE
Make it easier to submit exercise and retry

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#220]
Hi,

I think it would be useful to be able to submit an exercise without scrolling all the way down to click the submit button. Could be implemented via a keybinding or even by having a button at the top of the page to submit as well as on the bottom (though keybinding is preferred).

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory!

I think this is a good suggestion, so I went ahead and binded the check answers button to CTRL+ALT+C (CMD+SHIFT+C for mac).

**Comment by yangmillstheory** [comment]
素晴らしい！ありがとうございます。
