### ISSUE TITLE
Mistakes in 第12課 - Useful Expressions: Doctor's Office Vocabulary

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#222]
Hey Seth,

Could you check if the answers to questions 1-8 are correct?

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/ba7afead-5c74-4cbd-87ad-cc3d0065250b)

My understanding is that all the professions should end with い. This is based on the Genki Lesson 12 田んぼ as well as Jisho; for example:

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/4559fc83-5b1a-4a90-b9be-a22d9d9fc8b2)

Thanks!

**Comment by SethClydesdale** [comment]
The vocabulary for this exercise is based on this page, but yeah, when talking about medical professions they normally end in -医. For some reason that suffix is left out here, so I'll look into updating it when I get the chance.

![Screenshot 2023-09-22 205909](https://github.com/SethClydesdale/genki-study-resources/assets/10122549/96009063-47b5-4ba4-b1de-00f0a4b6f83c)

**Comment by SethClydesdale** [comment]
This should be corrected now!
