### ISSUE TITLE
Lesson 16: 〜といいですね possible mistake

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#231]
Hi Seth,

<img width="540" alt="image" src="https://github.com/SethClydesdale/genki-study-resources/assets/2729079/95c94f18-d39d-4a20-aa31-56b605f5edf8">

For this exercise, why isn't the particle を accepted? Googling around, it seems that を is the appropriate particle to use after the direct object when using もらう.

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory!

For most potential verbs (can… form) が is usually used. Apparently を can be used nowadays in some cases, but formerly が was the only correct particle to use with potential verbs.

**Comment by yangmillstheory** [comment]
OK, thanks. By the way, what's the source of truth for the answers on your website?

**Comment by SethClydesdale** [comment]
They come directly from the answer key for the textbooks. I believe there also a few where I wrote my own answer as well.
