### ISSUE TITLE
Answer for lessons/lesson-3/workbook-7 - Question 6

### ISSUE THREAD

**Issue by robmaeda** [SethClydesdale/genki-study-resources#232]
Takeshi sometimes drinks coffee at that cafe.

Current answer: たけしさんは時々あのカフェでコーヒーを飲みます。

I would have expected this to use その instead of あの since we have no context and it only says "that cafe" instead of "that cafe over there." I'm only a beginner though, so does あの make more sense here/is it more likely to be used in this situation?

Thank you for this great resource btw!

**Comment by SethClydesdale** [comment]
Hello, sorry for the late reply!

It depends on context, but ultimately あの is used when the object is nowhere close to the speaker and listener, and その when the object is close to the listener. I believe in this context, the cafe is nowhere near you or Takeshi. I'll look into perhaps adding a context clue to this one!

**Comment by SethClydesdale** [comment]
done!
