### ISSUE TITLE
Freeform sentence replies should consistently require or not require a period

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#234]
For example, in this one:

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/3500a660-1b56-46da-a70e-d77adbe2f6ef)

Some of the answers already have a period supplied, while others don't. For consistency's sake, it might make sense to always add a period at the end. Note that some answers require a period in the middle, but this shouldn't prevent consistency.

**Comment by SethClydesdale** [comment]
Hello!

I can see what you mean, so it probably would be a good idea to add a period on the end of these problems. If you encounter any, please feel free to let me know which exercises they're in so I can correct them! You're also free to make a PR for these if you like as well.
