### ISSUE TITLE
"I heard it's a tough job, but it looks interesting" - wrong translation

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#236]
I think the last answer on https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-17/workbook-6/ is wrong.

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/3de70788-bf83-475a-916b-b2339199c959)

The given answer translates to "It _looks like_ a tough job, but it looks interesting." I think the correct translation is 

>仕事は大変だそうですが、面白そうです。

**Comment by SethClydesdale** [comment]
Hello, thanks for reporting this!

It looks like a mistranslation since the sample answer doesn't utilize だそう. I've corrected it to "It seems to be a tough job, but it looks interesting."
