### ISSUE TITLE
第19課 - Workbook: ～はずです: III-2 is unanswerable

### ISSUE THREAD

**Issue by yangmillstheory** [SethClydesdale/genki-study-resources#240]
The answer to the aforementioned question is unknowable (without psychic powers):

![image](https://github.com/SethClydesdale/genki-study-resources/assets/2729079/d086bd24-30af-446a-81e5-13a2593a77f8)

**Comment by SethClydesdale** [comment]
Hello @yangmillstheory, thanks for bringing this to my attention! I'll look into possibly adding a cue for this question when I get the chance.
