### ISSUE TITLE
Furigana typo in Lesson 9 - Grammar 3 - Q17

### ISSUE THREAD

**Issue by altairvegub** [SethClydesdale/genki-study-resources#244]
Found this typo in [Lesson 9 - Grammar 3](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-9/grammar-3/) for question 17.

![](https://i.imgur.com/q8EaLiX.png)

Furigana says きる rather than くる. Not sure if the issue is from the furigana logic itself or if it's question specific.

**Comment by SethClydesdale** [comment]
Hello @altairvegub!

That should indeed be くる, I went ahead and corrected this typo now. Thanks for reporting it!
