### ISSUE TITLE
Incorrect answer in the 第7課 - Practice: ～ている (Actions in Progress)

### ISSUE THREAD

**Issue by NguyeHongPh** [SethClydesdale/genki-study-resources#250]
![Screenshot 2024-02-16 173430](https://github.com/SethClydesdale/genki-study-resources/assets/118801428/ced6f55b-321b-4676-89bc-d1e120cf3fe9)
The answer to this question is wrong 中国語　is Chinese, not Japanese in this situation

**Comment by SethClydesdale** [comment]
Hello @NguyeHongPh, thank you for reporting this. That definitely shouldn't be marked as a correct answer, so I went ahead and fixed it now!
