### ISSUE TITLE
Font or style issues, displaying all text with "?"

### ISSUE THREAD

**Issue by Splish-Splash** [SethClydesdale/genki-study-resources#254]
This site worked well yeaterday, but know it is displayed like this, I am not sure if it's my problem or some recent updates.
system: Mac, 
browser: Google Chrome

<img width="1390" alt="image" src="https://github.com/SethClydesdale/genki-study-resources/assets/56451080/91495997-7182-4097-9487-eeca7cccf3cd">

**Comment by SethClydesdale** [comment]
Hello @Splish-Splash!

I did a few tests on a number of browsers and Windows/Linux, and everything appears to be in working order, so it may be a system level issue. After performing a quick search, I found that it's a fairly common problem with the Mac OS. [This topic](https://discussions.apple.com/thread/254794264?sortBy=best) from the Apple Support Community appears to offer a number of solutions, but if that doesn't help, there's a plethora more of topics concerning this issue under [these search parameters](https://www.google.com/search?q=font+suddenly+all+question+marks+mac).

I would try to assist you more, but unfortunately I'm not familiar with the Mac OS. At the very least, I hope the information above will be of some use to you!

**Comment by Splish-Splash** [comment]
> Hello @Splish-Splash!
> 
> I did a few tests on a number of browsers and Windows/Linux, and everything appears to be in working order, so it may be a system level issue. After performing a quick search, I found that it's a fairly common problem with the Mac OS. [This topic](https://discussions.apple.com/thread/254794264?sortBy=best) from the Apple Support Community appears to offer a number of solutions, but if that doesn't help, there's a plethora more of topics concerning this issue under [these search parameters](https://www.google.com/search?q=font+suddenly+all+question+marks+mac).
> 
> I would try to assist you more, but unfortunately I'm not familiar with the Mac OS. At the very least, I hope the information above will be of some use to you!

Thanks, I updated the system and it maybe somehow cleared all cache and helped me.
