### ISSUE TITLE
wrong answer

### ISSUE THREAD

**Issue by NguyeHongPh** [SethClydesdale/genki-study-resources#255]
In the 第9課 - Workbook: Quotations, i think the answer for this question is wrong:
I think Tadashi's father was good-looking when he was young: ただしさんのお父さんは若い時、かっこよ**かったと思います**
-> It should use **と思います** not **かったと思います**

**Comment by SethClydesdale** [comment]
Hello @NguyeHongPh,

The かった here is from the past form of かっこいい／かっこよい (good-looking) which conjugates to かっこよかった (was good-looking).

**Comment by NguyeHongPh** [comment]
My bad, thanks for your reply.
