### ISSUE TITLE
The answer should be/can be kanji 

### ISSUE THREAD

**Issue by NguyeHongPh** [SethClydesdale/genki-study-resources#256]
![image](https://github.com/SethClydesdale/genki-study-resources/assets/118801428/2305d50e-3589-465f-8dc5-d12ecce65fe5)
In this question in the Workbook: ～たり～たりする , the word あした can be written as 明日. I think the answer should also include the kanji option as well

**Comment by SethClydesdale** [comment]
Hello @NguyeHongPh, I went ahead and updated this answer to include the kanji for 明日. Thanks for the report!
