### ISSUE TITLE
Anki Deck Vocab Not In Order

### ISSUE THREAD

**Issue by MinamiHasaki** [SethClydesdale/genki-study-resources#260]
When downloading the Anki decks from the official site or repo, the vocabulary isn't in order. 

I went looking around the repo for an answer and found this PR (#137). According to this, it seems like the notes should be in order but they aren't. After downloading the repo and deleting the deck, kanji, and wordlist directories, regenerating the deck locally fixed the order problem.

**Comment by SethClydesdale** [comment]
Hello @MinamiHasaki, thank you for reporting this! I'll look into correcting this sometime later this week using the method you described 👍

**Comment by SethClydesdale** [comment]
Hi again! I just pushed https://github.com/SethClydesdale/genki-study-resources/commit/833b56253f8ac8e8c125d16c08f7646f4341d6aa in an attempt to address this issue. If the vocab is still not in order, please let me know.

**Comment by MinamiHasaki** [comment]
I just quickly checked two of the decks, and the order seems to be fixed!

**Comment by SethClydesdale** [comment]
Awesome! Thanks for confirming 👍
