### ISSUE TITLE
Missing えん

### ISSUE THREAD

**Issue by lambdacore12** [SethClydesdale/genki-study-resources#263]
Genki study resources（2nd edition） - 第3課 - Kanji Practice: Prices　
There is a missing えん in the correction of question number 11:

![Capture d'écran 2024-04-15 144751](https://github.com/SethClydesdale/genki-study-resources/assets/37704802/57808719-b762-4f1d-be0d-a4ad3b278d9e)

**Comment by SethClydesdale** [comment]
Hello @lambdacore12!

Thank you for reporting this; it should be corrected now!
