### ISSUE TITLE
Correct Answer Marked Incorrect In 第4課 - Practice: ～時間

### ISSUE THREAD

**Issue by cagwood** [SethClydesdale/genki-study-resources#266]
In the question "waited for Takeshi/1 hour", the answer is "メアリーさんは一時間たけしさんを待ちました。"
Another option, "メアリーさんはたけしさんを一時間待ちました。", is marked wrong.
I think both of these options are correct since the book uses the following as an example in 4.6:
"メアリーさんはそこでたけしさんを一時間待ちました。"
So, the position of "一時間" is flexible.

**Comment by SethClydesdale** [comment]
Hello @cagwood, thank you for reporting this!

You're correct, the time can come before or after the を particle here. I went ahead and corrected this now!
