### ISSUE TITLE
Optional Hiragana/Katakana only for text

### ISSUE THREAD

**Issue by ccrenfroe** [SethClydesdale/genki-study-resources#273]
As the lessons advance, some kanji seems to get introduced, and in some lessons is used exclusively. Would it be a useful feature to have this be something that could be toggled, such that the user has the option to continue their studies with only hiragana or to further challenge themselves by then switching to kanji?

**Comment by SethClydesdale** [comment]
Hello, sorry for the late reply!

It's something to consider, though, I believe the option to toggle furigana already accomplishes this by providing helper texts under the kanji to display its reading. I know the 2nd edition lacked this when I first worked on it, but the 3rd edition should have full support. For any kanji that may lack furigana, I'd recommend using the built-in dictionary or an extension, such as [Yomichan](https://foosoft.net/projects/yomichan/), to quickly see the reading/meaning.
