### ISSUE TITLE
Words in wrong Anki decks?

### ISSUE THREAD

**Issue by zhengman777** [SethClydesdale/genki-study-resources#274]
Sorry if I’m just missing something. I recently started reading Genki 3rd edition and using the Anki decks (for third edition). In Lesson 3’s deck, there are cards about counting people (eg 8人) and in Lesson 4’s deck there are cards about vocab like fireworks (花火) which are not taught at that point in Genki.

**Comment by SethClydesdale** [comment]
Hello @zhengman777!

Those vocab cards are most likely from the [kanji vocab](https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/#literacy-4), which are words taught in the reading and writing section of the textbook for that lesson (it's the section in the back of the textbook).

**Comment by zhengman777** [comment]
Ahh ok! Thanks!
