### ISSUE TITLE
Bug with hiragana listening practice?

### ISSUE THREAD

**Issue by Mar941545** [SethClydesdale/genki-study-resources#280]
Hi been filling in the hiragana practice exercises. I noticed on the hiragana practice (dots/circles/small やゆよ) it marks this as red but it looks to be correct? Same happens in the exercise below it with the small ones.
![Screenshot_20240823_202450_Chrome](https://github.com/user-attachments/assets/4b024641-503b-4bb0-9080-30a138aced54)

**Comment by SethClydesdale** [comment]
Hello, @Mar941545!

The small fields in this exercise take the small variants of their kana. With romaji input, you can create them by prefixing the kana with "x" like this: xya for ゃ, xyo for ょ, etc. For kana input, such as on a phone, there should be a button to change the size of the kana which normally is represented by 小 (small).

**Comment by Mar941545** [comment]
Ah thank you
I don't know how I missed this bit in the instruction 🙈

**Comment by SethClydesdale** [comment]
You're welcome! 

It happens haha. Best of luck on your studies!
