### ISSUE TITLE
Mistype in example sentence lesson 5

### ISSUE THREAD

**Issue by luca-brambilla** [SethClydesdale/genki-study-resources#281]
Hi!

In lesson 5 exercise II.D, there is a mistype: 休み is missing み and the furigana in the example sentence

https://sethclydesdale.github.io/genki-study-resources/lessons-3rd/lesson-5/grammar-8/

:)

**Comment by SethClydesdale** [comment]
Hello, @luca-brambilla!

Thank you for reporting this typo. It should be corrected now!

If you notice anything else like this, please don't hesitate to open a new issue.
