### ISSUE TITLE
Regarding "NOTE" in 第0課 - Hiragana: Diacritical Marks

### ISSUE THREAD

**Issue by pugpenguin** [SethClydesdale/genki-study-resources#289]
I think which sound is used by which characters is mixed up here.
![Screenshot 2024-11-22 001127](https://github.com/user-attachments/assets/22c26b2b-4e22-4894-a8bb-9bc673e1b25d)

**Comment by pugpenguin** [comment]
I may be wrong though and maybe this specific exercise(Multiple Choice) just tells the wrong sounds these characters make.

**Comment by SethClydesdale** [comment]
Hello @pugpenguin,

These four kana are part of what's called the [Yotsugana](https://en.wikipedia.org/wiki/Yotsugana). In modern standard Japanese, ぢ & じ and づ & ず are pronounced virtually the same. The only difference you might see is in their romanizations dzi/di for ぢ and dzu/du for づ.

**Comment by pugpenguin** [comment]
Thank you so much

**Comment by SethClydesdale** [comment]
You're welcome!

If you ever have another question or problem feel free to contact me again. Wishing you the best on your studies!
