### ISSUE TITLE
Typo chapter 18

### ISSUE THREAD

**Issue by ClausLJ** [SethClydesdale/genki-study-resources#29]
On page

https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-18/literacy-8/

The sentence-part
今の彼女にも会**い**えたんですよ contains an い that is not in the textbook.

Thanks again for the great study resources!

Br
Claus

**Comment by SethClydesdale** [comment]
Hi @ClausLJ,

Nice catch! That typo should be corrected now. ✔️  

No problem, thanks for the report!

Have a good day.
