### ISSUE TITLE
Lesson 5 Te-Form Conjugation 1

### ISSUE THREAD

**Issue by zoro11031** [SethClydesdale/genki-study-resources#30]
Hi, just wanted to let you know of a small mistake for the answer to one of the questions.

For the te form of 来る, the app is showing the answer as 着て instead of 来て. Thanks for all your work!

**Comment by SethClydesdale** [comment]
Hi @zoro11031,

Thanks a lot for reporting this typo! It should be corrected now. ✔️ 

Have a great day. :)
