### ISSUE TITLE
Incorrect answer in Lesson 2 - Numbers 4 activity

### ISSUE THREAD

**Issue by kelvinx** [SethClydesdale/genki-study-resources#31]
Hi, there seems to be an incorrect answer in this [activity](https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-2/numbers-4/): 1,300 should be せんさんびゃく and not せんさんひゃく. Thank you for the amazing resource!

![image](https://user-images.githubusercontent.com/1611788/71767255-5ce27e00-2f5e-11ea-8003-c1c540daa5fa.png)

**Comment by SethClydesdale** [comment]
Hello @kelvinx,

Thank you for reporting this incorrect answer! It should be corrected now. ✔️ (might have to clear your cache if not)

Thanks again, and have a good day. :)
