### ISSUE TITLE
Typos in Lesson 13

### ISSUE THREAD

**Issue by jahammond11** [SethClydesdale/genki-study-resources#32]
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-13/literacy-3/
The wrong kanji is being used for 飯 in the header and sidebar. 販 needs to be 飯.

https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-13/literacy-9/
In the beginning: "日本に乗て" is supposed to be "日本に来て".

https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-13/literacy-wb-4/
The hiragana for 空気 is wrong and should be くうき, not こうき.

https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-13/literacy-wb-6/
Question 8's kanji is wrong and is supposed to be 一生, not 一年.

**Comment by SethClydesdale** [comment]
Hello @jahammond11,

Thank you for reporting these typos! They should all be corrected now. ✔️ 

Thanks again for your help and have a good day.
