### ISSUE TITLE
第3課 - Workbook: Noun を Verb

### ISSUE THREAD

**Issue by kathleenbanawa** [SethClydesdale/genki-study-resources#34]
There appears to be a typo in the kanji version of the correct answer for question 4:

I don't drink tea.
わたしはおちゃを**のみません**
私はお茶を**飲みます**

The hiragana version reads のみません which is correct, but the kanji version reads 飲みます (affirmative form) instead.

**Comment by SethClydesdale** [comment]
Hello @kathleenbanawa,

Thank you for reporting this mistake! It should be corrected now. ✔️ 

Have a good day. :)
