### ISSUE TITLE
One giving and receiving Q missing correct answer

### ISSUE THREAD

**Issue by kwakkles** [SethClydesdale/genki-study-resources#35]
One of the grammar points in Genki's lesson 14 is about giving and receiving, using the right word for the action, and which direction the giving and receiving goes. 
In 第14課 - Practice: あげる／くれる／もらう at
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-14/grammar-6/
there are 11 questions. All 11 questions offer four responses to answer. 10 of them have two correct answers each, with one being for who received the item and the other for who gave it. 
The one that doesn't have two correct answers, question # 2 in the order of 11, grades with only one correct answer. There are two corrects answer, though. I believe the other correct answer is:

ディエゴさんは私にチョコレートをもらいました。

When I answer with that option, it is graded as wrong. But that cannot be so. It is a grammatically correct sentence and true to the facts of the scenario.

**Comment by SethClydesdale** [comment]
Hello,

Thanks for your concern. In regards to the answer being incorrect, I believe it has to do with point 3 on page 57.

![](https://i.imgur.com/ffCBrT2.png)

Genki's explanation is a little convoluted, but basically もらう is seen from the receiver's point of view, so when it comes to the first person, _others_ usually don't receive things from _you_.

**Comment by kwakkles** [comment]
Okay. Thanks for the explanation.

**Comment by SethClydesdale** [comment]
No problem. Have a good day. :)
