### ISSUE TITLE
Chapter 20 typo

### ISSUE THREAD

**Issue by ClausLJ** [SethClydesdale/genki-study-resources#36]
Hi

I found just one typo in the Cat's Plate:
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-20/literacy-7/

In the first line of the main text, the first occurence of 代 should be changed to　以.

Br
Claus

**Comment by SethClydesdale** [comment]
Hello @ClausLJ,

Thank you for the report! That typo should be corrected now. ✔️

Have a good day!
