### ISSUE TITLE
乗る has particle に

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#37]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-19/grammar-2/
Erroneous content
山下先生はバスをお乗りになります。
Correction of the content
山下先生はバスにお乗りになります。

The Genki "Answer Key" also writes it with に.

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the reports! The particle for this answer should be corrected now. ✔️ 

Have a good day.
