### ISSUE TITLE
Book uses きのう instead of きょう

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#38]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-19/grammar-3/

Erroneous content
きょう何を召し上がりましたか。
Correction of the content
きのう何を召し上がりましたか。
While grammatically correct the exercise in the book uses きのう.

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Nice catch, きょう should be changed to きのう. ✔️ 

Thanks again for the reports.

Have a good day.
