### ISSUE TITLE
Kanji "せんたく" in this context "to wash"

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#39]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-19/grammar-7/
Erroneous content
一人で住んでいるから、自分で選択や掃除をするはずです。
Correction of the content
一人で住んでいるから、自分で洗濯や掃除をするはずです。
Also in the other 2 (wrong) answers.

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the report! The typo should be corrected now. ✔️ 

Thanks again for the help and have a good day. 👍
