### ISSUE TITLE
Stray komma

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#40]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-19/workbook-3/
Erroneous content
右、をご覧ください。富士山(Mt.Fuji)が見えます。
Correction of the content
右をご覧ください。富士山(Mt.Fuji)が見えます。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Nice catch! It should be removed now. ✔️ 

Thanks for the help.
