### ISSUE TITLE
Missing この and 六時

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#52]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-16/workbook-1/
Erroneous content
ホストファミリーのお母さんに漢字を教えてもらいます。
ルームメートに起こしてもらいます。
Correction of the content
ホストファミリーのお母さんにこの漢字を教えてもらいます。
ルームメートに六時に起こしてもらいます。

All the answers you've given in 16.1 (both I and II) differ from the answer key.

**Comment by SethClydesdale** [comment]
The answer key for the second edition (latest revision) omits these, however, they could be added in as optional phrases. Which I'll probably do, because they still make sense.

![](https://i.imgur.com/AEqG7Zw.png)

Which edition of the answer key are you using?
