### ISSUE TITLE
Both kanji and hiragana answer use とき

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#54]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-16/workbook-8/
Erroneous content
はい、よく泣きます。感動したとき、泣きます。
Correction of the content
はい、よく泣きます。感動した時、泣きます。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for all the reports! For future reports, if you encounter anymore mistakes, feel free to use the [edit button](https://i.imgur.com/TP4VSfJ.png) to add the additional information to your issue, so you get something [like this](https://github.com/SethClydesdale/genki-study-resources/issues/32), for example. (You can also wait and post a report in bulk if it's easier)

Keeping to a single issue/thread, if the reports are of a similar nature, is usually easier to manage. Of course, opening a new issue is fine if your last one was closed. Don't worry about the ones that are already open, I'll make sure to handle all of them sometime tomorrow morning over some coffee. ☕️  

Thanks again for the help, appreciate it! 👍

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

All the issues you reported should be corrected now. ✔️ 

Thanks for the help. 👍 

ref: #41 #42 #43 #44 #45 #46 #47 #48 #49 #50 #51 #52 #53
