### ISSUE TITLE
Spelling わかりません

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#55]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-20/grammar-7/
Erroneous content
さあ、子供がいるかどうかわりません。
Correction of the content
さあ、子供がいるかどうかわかりません。
Same for the other (wrong) answer.

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the report! The missing か on this question should be fixed now. ✔️ 

Have a good day.
