### ISSUE TITLE
Being polite

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#56]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-15/grammar-4/
Erroneous content
たけしのお母さんは保険に入っておきます。
Correction of the content
たけしさんのお母さんは保険に入っておきます。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the report! The missing honorific has been fixed. ✔️ 

Have a good day.
