### ISSUE TITLE
16 more mistakes in textbook

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#57]
When people try to help you out by sending in corrections I don't think you should be too picky about what format it comes in.

Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-15/grammar-6/
Erroneous content
これはベートーベンが引いたピアノです。
Correction of the content
これはベートーベンが弾いたピアノです。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-14/grammar-9/
Erroneous content
メアリーさんはハンバーガを一個しか食べませんでした。
Correction of the content
メアリーさんはハンバーガーを一個しか食べませんでした。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/grammar-6/
Erroneous content
八時にうち出なければいけません。
Correction of the content
八時にうちを出なければいけません。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/grammar-6/
Erroneous content
九時に授業を出なければいけません。
Correction of the content
九時に授業に出なければいけません。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/grammar-6/
Erroneous content
二時英語を教えなければいけません。
Correction of the content
二時に英語を教えなければいけません。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-10/grammar-2/
本州がいちばん大きいです。
Erroneous content
北海道がいちばん大きいです。
Correction of the content
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/grammar-3/
Erroneous content
ざびしくなかった
Correction of the content
さびしくなかった
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-9/grammar-7/
Erroneous content
お父さんは、友だちよく踊りに行ったと言っていました。
Correction of the content
お父さんは、友だちとよく踊りに行ったと言っていました。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-8/grammar-7/
Erroneous content
ええ，暑いと思います。
Correction of the content
ええ、暑いと思います。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-7/grammar-2/
Erroneous content
お父さんは四十八歳です
Correction of the content
お父さんは四十八歳です。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-7/grammar-4/
Erroneous content
いいえ、山田さんは太ってません。
Correction of the content
いいえ、山田さんは太っていません。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-5/grammar-7/
Erroneous content
レストランはしずかじゃなかったです。
Correction of the content
レストランは静かじゃなかったです。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-4/grammar-2/
Erroneous content
ほんはつくえの上です。
Correction of the content
本はつくえの上です。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-4/grammar-8/
Erroneous content
メアリーさんは英語を話します。スパイン語も話します。
Correction of the content
メアリーさんは英語を話します。スペイン語も話します。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-3/grammar-6/
Erroneous content
音楽を聴きませんか。
Correction of the content
音楽を聞きませんか。
 
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-1/grammar-1/
Erroneous content
ロンドンだいかくのがくせい
Correction of the content
ロンドンだいがくのがくせい

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for reporting all of these! I'll look into correcting everything sometime tomorrow morning. 

Also, apologies if I came off as picky or inconsiderate about the formatting of reports. It was only a suggestion, as it's much easier/quicker to manage and fix things like these when they're consolidated into a single issue, like you've done here. 👍 

Regardless, I still appreciate you taking the time to report these problems, so thanks.

**Comment by SethClydesdale** [comment]
Hello again @AyaVK,

All the problems you reported should be corrected now. ✔️ 

Thanks a bunch.
