### ISSUE TITLE
Workbook

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#59]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/workbook-5/
Erroneous content
来週テストの試合があるので、練習しなければいけません。
Correction of the content
来週テニスの試合があるので、練習しなければいけません。

Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-12/workbook-7/ 
Erroneous content
あしたは雨でしょう。
Correction of the content
あしたは雨です。
My version of answer key uses です.

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for reporting these! They both should be corrected now. ✔️ 

You're correct that "あしたは雨でしょう" should use です, that's how it's written in my key as well. Not sure where I got でしょう from lol. 🤔 

Have a good day.
