### ISSUE TITLE
bank spelled incorrectly in quiz - Lesson 2, vocab 4

### ISSUE THREAD

**Issue by DavidBurela** [SethClydesdale/genki-study-resources#6]
**Issue:**
The json has it defined as
'ぎん**ご**う' : 'bank',
instead of 
'ぎん**こ**う' : 'bank',
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-2/vocab-4/

**Reference:**
Genki 1, page 61

P.S. I could have submitted this a Pull request.  For future reference do you prefer issues submitted, or PRs for small mistakes?

**Comment by SethClydesdale** [comment]
Hi @DavidBurela,

Thanks for the report! I went ahead and fixed the typo. 👍 

Ah yes, a pull request would be just fine! I made sure to update the report page to reflect that for any future contributors.
