### ISSUE TITLE
プレゼント

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#61]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-21/grammar-3/
Erroneous content
プレセントが包んであります。
Correction of the content
プレゼントが包んであります。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the correction. This typo should be fixed now. ✔️ 

Have a good weekend.
