### ISSUE TITLE
Page 81 says 昼寝

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#62]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-21/workbook-5/
Erroneous content
昼ご飯をしている間に猫が家に入りました。
Correction of the content
昼寝をしている間に猫が家に入りました。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the corrections! This typo should be fixed now as well. ✔️ 

Have a good weekend.
