### ISSUE TITLE
Sentence # 3 on page 114 mistake

### ISSUE THREAD

**Issue by kwakkles** [SethClydesdale/genki-study-resources#63]
Sentence # 3 on page 114 mistake:
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-15/literacy-wb-6/
Erroneous content
はっして
Correction of the content
はしって

**Comment by SethClydesdale** [comment]
Hello @kwakkles,

Thank you for the correction! This typo should be fixed now. ✔️ 

Have a good day.
