### ISSUE TITLE
第3課 - Practice: Time References 2

### ISSUE THREAD

**Issue by jlmelb** [SethClydesdale/genki-study-resources#65]
Hi,

First of all, just wanted to say I am really loving the website as it helps with my grammar study a lot - so thank you so much for creating this.

I am just starting out so apologise if I have gotten this wrong but it looks like for Q6 Finish the sentence「うちでテレビを見ます」by adding the time: tonight - the answer should be "今晩うちでテレビを見ます” instead of "今晩にうちでテレビを見ます”.  I'm basing this off that the notes said the particle should not be used with time expressions defined relative to the present moment.

Again, fully apologise if I have misunderstood this!

Cheers,
Joel

**Comment by SethClydesdale** [comment]
Hello @jlmelb,

Thank you for bringing this to my attention. You're correct, に should not be used with 今晩 in this sentence. I went ahead and fixed the correct answer for this question. ✔️ 

Have a good day!
