### ISSUE TITLE
第4課 - Workbook: Ｘがあります／います

### ISSUE THREAD

**Issue by jlmelb** [SethClydesdale/genki-study-resources#67]
Hi @SethClydesdale 

For Question 8. 日本に友だちがいますか。

Would a third answer such as はい、たくさん友達がいますbe a valid answer?

I'm just going off the Expressions of Quantity section where you can use たくさん to a direct object of a sentence.

**Comment by SethClydesdale** [comment]
Hello @jlmelb,

Yes, it should be valid. In fact, I just checked the 3rd Ed. and they added [this line](https://i.imgur.com/CIbwUXE.jpg) to the たくさん grammar point in lesson 4.
> You can also use both these orders (quantity-noun-particle and noun-particle-quantity) in ある and いる sentences.
>
> 野菜が**たくさん**あります。
> **たくさん**野菜があります。
>
> There are a lot of vegetables.

Though one other thing I'd like to mention is that you may encounter instances where たくさん**の**友達がいます is used instead. I believe this is more common in regards to describing the quantity/size of a living group (like 人), but the former (without の) is still grammatically correct and people should understand what you're saying.

**Comment by SethClydesdale** [comment]
Hello,

As it has been more than a month without activity on this issue, I'll mark it closed for now. Feel free to let me know if you would like to reopen this issue.
