### ISSUE TITLE
Particle を

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#68]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-22/grammar-6/
Erroneous content
薬お飲めば、元気になります。
Correction of the content
薬を飲めば、元気になります。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the correction! This typo should be fixed now. ✔️ 

Have a good day.
