### ISSUE TITLE
こと

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#69]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-22/grammar-8/
Erroneous content
日本に留学したごとがないのに、日本語がぺらぺらです。
Correction of the content
日本に留学したことがないのに、日本語がペラペラです。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the correction! This typo should be fixed now. ✔️ 

Have a good day.
