### ISSUE TITLE
メアリーさん

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#70]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-23/grammar-7/
Erroneous content
メアリさんは週末に図書館で勉強することにしています。
Correction of the content
メアリーさんは週末に図書館で勉強することにしています。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the corrections! The mistakes in this exercises should be fixed now. ✔️ 

Have a good day.
