### ISSUE TITLE
Particle

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#71]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-23/grammar-7/
Erroneous content
メアリーさんはわからない時、人を聞くことにしています。
Correction of the content
メアリーさんはわからない時、人に聞くことにしています。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thank you for the corrections! The mistakes in this exercises should be fixed now. ✔️ 

Have a good day.
