### ISSUE TITLE
場所

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#72]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-23/workbook-4/
Erroneous content
その所が安全でも、注意したほうがいいです。
その所が安全でも、気をつけたほうがいいです。
Correction of the content
その場所が安全でも、注意したほうがいいです。
その場所が安全でも、気をつけたほうがいいです。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thanks again for correcting these mistakes! They should be fixed now. ✔️ 

Have a good weekend.
