### ISSUE TITLE
も?

### ISSUE THREAD

**Issue by AyaVK** [SethClydesdale/genki-study-resources#73]
Link to the page that contains the mistake(s)
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-23/workbook-8/
Erroneous content
サラダにも入れてもいいですよ。
Correction of the content
サラダに入れてもいいですよ。

**Comment by SethClydesdale** [comment]
Hello @AyaVK,

Thanks again for correcting these mistakes! They should be fixed now. ✔️ 

Have a good weekend.
