### ISSUE TITLE
Question # 3 on page 134, V-A mistake

### ISSUE THREAD

**Issue by kwakkles** [SethClydesdale/genki-study-resources#74]
Question # 3 on page 134, V-A mistake:
https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-17/grammar-6/
Erroneous content
耳かぎ
Correction of the content
耳かき

**Comment by SethClydesdale** [comment]
Hello @kwakkles,

Thank you for the correction! This typo should be fixed now. ✔️ 

Have a good day.
