### ISSUE TITLE
暖冬 means warm winter, not warn winter

### ISSUE THREAD

**Issue by kwakkles** [SethClydesdale/genki-study-resources#78]
Found in: Quick Dictionary, accessed by clicking on the book picture at the bottom right corner.
読L19-漢字表

暖冬
だんとう
warn winter

Erroneous content
warn
Correction of the content
warm

**Comment by SethClydesdale** [comment]
Hello @kwakkles,

Nice catch! I'll push a fix online for this typo soon. Thanks for reporting it! 👍

**Comment by SethClydesdale** [comment]
This typo should now be corrected. ✔️ 

Thanks again!
