### ISSUE TITLE
Hiragana romaji discrepancies

### ISSUE THREAD

**Issue by wshirey** [SethClydesdale/genki-study-resources#86]
First of all, thanks for the tool! It's great!

While doing a hiragana quiz, I found a few discrepancies from the romaji spelling of certain characters in the 3rd edition of book and your tool:

hiragana|Genki romaji|Genki Study Resource romaji
-|-|-
づ |zu|du
ぢ|ji|di

I understand that the `du/di` romaji is what you use to type into the Japanese keyboard for these characters, but for learners, would it be best to stick to what the book recommends?

**Comment by SethClydesdale** [comment]
The note should now be displayed in each of the exercises where ぢ、づ、ヂ、and ヅ are present.

**Comment by wshirey** [comment]
Awesome. That works! Thanks!

**Comment by SethClydesdale** [comment]
Great to hear, you're welcome! 😄 

All the best on your studies 👊
