### ISSUE TITLE
Errors in Lesson 4 and Lesson 5

### ISSUE THREAD

**Issue by jahammond11** [SethClydesdale/genki-study-resources#9]
Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-4/workbook-1/
Error: Question 5's answer is wrong. It should be 私は子供が**います**, not 私は子供が**あります**. Double checked and verified this with the official answer book and it says the former.

Page: https://sethclydesdale.github.io/genki-study-resources/lessons/lesson-5/literacy-5/
Error: The kanji for the word 'travel' is wrong. It should be 旅行, not 両行. Also, the furigana is incorrect and needs to be りょこう instead of りょうこう.

**Comment by SethClydesdale** [comment]
Hello @jahammond11,

Thanks a bunch for reporting these errors! They should now be corrected. ✔️

Have a good day.
